# Generated by Django 5.2.3 on 2025-06-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название плейлиста', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, help_text='Время начала действия плейлиста (опционально)', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Время окончания действия плейлиста (опционально)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли это назначение плейлиста')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_playlist', to='core.device')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Порядок показа контента в плейлисте (начиная с 0)')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduler.playlist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
    ]
