# Generated by Django 5.2.3 on 2025-06-28 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название контента (для админки)', max_length=255)),
                ('content_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], help_text='Тип контента', max_length=10)),
                ('file', models.FileField(help_text='Загрузите файл изображения или видео', upload_to='content/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Длительность показа для изображений в секундах (для видео не требуется)', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Название сервисного центра или ТВ', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Адрес или местоположение', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли устройство')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Время последнего подключения к серверу')),
            ],
        ),
    ]
