# Generated by Django 5.2.3 on 2025-06-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(blank=True, help_text='Версия приложения Digital Signage на устройстве', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP-адрес устройства', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC-адрес устройства (если доступен)', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Серийный номер ТВ', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальный ключ для регистрации нового устройства', max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Был ли этот ключ уже использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(blank=True, help_text='Устройство, которое зарегистрировалось с этим ключом', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
            ],
        ),
    ]
